sudo: false
dist: bionic
language: python
python: 3.7
install:
  - pip install pipenv
  - pip install pytest-cov
  - pip install codecov
  - pipenv install --dev
script:
  - black --check **/*.py
  - pipenv run checks
  - pipenv run tests --cov=./
after_success:
  - codecov
